### ISSUE TITLE
tax receipt revamp

### ISSUE THREAD

**Issue by bwdmonkey** [CodeTheChangeUBC/reBOOT#278]
### Requirements

- [x] tax receipt policy https://github.com/CodeTheChangeUBC/reBOOT/issues/279
- [x] tax receipt style upgrade https://github.com/CodeTheChangeUBC/reBOOT/issues/277
- [x] tax receipt donor statistics counter box https://github.com/CodeTheChangeUBC/reBOOT/issues/241
- [x] counter statistics clarification #281
